<?php

namespace App\Models\Amtelco\Genesis;

use Exception;

class UnSelAuto extends GenesisStat
{
    public static function amtelcoStatisticDefinition(): string
    {
        return 'The total Unselected time for calls in the Auto state. The Auto Call State is used during Autodial calls generated by Auto Dispatch and when one of the following behaviors is being performed: ACD Callback, Agent Audio, Announce ANI, Announce Time, Auto Attendant, Bye, Change Client, Closed, Conference Bridge, Directory Assistance, Follow Me, Listing Lookup, MergeComm, Navigation Menu, Page Confirmation, Park Orbit, Quick Checkin, Rauland, Seek Operator, Smart Paging, Status Checkin, or Voice Mail Checkin';
    }
    public function amtelcoSqlCommand(): string
    {
        return
            <<<TSQL
        select 'TODO';
        TSQL;
    }

    public function amtelcoSqlParams(): array
    {
        return [];
    }
}
